# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: barbot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61rbot.proto\"2\n\x0cOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tdrink_num\x18\x02 \x01(\x05\"\x19\n\nOrderReply\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t24\n\x06\x42\x61rbot\x12*\n\nPlaceOrder\x12\r.OrderRequest\x1a\x0b.OrderReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'barbot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERREQUEST._serialized_start=16
  _ORDERREQUEST._serialized_end=66
  _ORDERREPLY._serialized_start=68
  _ORDERREPLY._serialized_end=93
  _BARBOT._serialized_start=95
  _BARBOT._serialized_end=147
# @@protoc_insertion_point(module_scope)
