# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import barbot_pb2 as barbot__pb2


class BarbotStub(object):
    """The BarBot service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/Barbot/PlaceOrder',
                request_serializer=barbot__pb2.OrderRequest.SerializeToString,
                response_deserializer=barbot__pb2.OrderReply.FromString,
                )
        self.CleanSystem = channel.unary_unary(
                '/Barbot/CleanSystem',
                request_serializer=barbot__pb2.CleanRequest.SerializeToString,
                response_deserializer=barbot__pb2.CleanReply.FromString,
                )
        self.SystemCheck = channel.unary_unary(
                '/Barbot/SystemCheck',
                request_serializer=barbot__pb2.SystemCheckRequest.SerializeToString,
                response_deserializer=barbot__pb2.SystemCheckReply.FromString,
                )


class BarbotServicer(object):
    """The BarBot service definition.
    """

    def PlaceOrder(self, request, context):
        """Sends a drink order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanSystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BarbotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=barbot__pb2.OrderRequest.FromString,
                    response_serializer=barbot__pb2.OrderReply.SerializeToString,
            ),
            'CleanSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanSystem,
                    request_deserializer=barbot__pb2.CleanRequest.FromString,
                    response_serializer=barbot__pb2.CleanReply.SerializeToString,
            ),
            'SystemCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemCheck,
                    request_deserializer=barbot__pb2.SystemCheckRequest.FromString,
                    response_serializer=barbot__pb2.SystemCheckReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Barbot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Barbot(object):
    """The BarBot service definition.
    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Barbot/PlaceOrder',
            barbot__pb2.OrderRequest.SerializeToString,
            barbot__pb2.OrderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Barbot/CleanSystem',
            barbot__pb2.CleanRequest.SerializeToString,
            barbot__pb2.CleanReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Barbot/SystemCheck',
            barbot__pb2.SystemCheckRequest.SerializeToString,
            barbot__pb2.SystemCheckReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
