# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: barbot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61rbot.proto\"5\n\nOrderTuple\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\x05\x12\x11\n\tamount_oz\x18\x02 \x01(\x01\"\x83\x01\n\x0cOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ndrink_name\x18\x02 \x01(\t\x12&\n\x11\x63ontainer_amounts\x18\x03 \x03(\x0b\x32\x0b.OrderTuple\x12\x13\n\x0b\x66lavor_name\x18\x04 \x01(\t\x12\x11\n\tflavor_id\x18\x05 \x01(\x05\"F\n\nOrderReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ndrink_name\x18\x02 \x01(\t\x12\x13\n\x0b\x66lavor_name\x18\x03 \x01(\t\"\x1f\n\x0c\x43leanRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x1d\n\nCleanReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"%\n\x12SystemCheckRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"#\n\x10SystemCheckReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t2\x9a\x01\n\x06\x42\x61rbot\x12*\n\nPlaceOrder\x12\r.OrderRequest\x1a\x0b.OrderReply\"\x00\x12+\n\x0b\x43leanSystem\x12\r.CleanRequest\x1a\x0b.CleanReply\"\x00\x12\x37\n\x0bSystemCheck\x12\x13.SystemCheckRequest\x1a\x11.SystemCheckReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'barbot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERTUPLE._serialized_start=16
  _ORDERTUPLE._serialized_end=69
  _ORDERREQUEST._serialized_start=72
  _ORDERREQUEST._serialized_end=203
  _ORDERREPLY._serialized_start=205
  _ORDERREPLY._serialized_end=275
  _CLEANREQUEST._serialized_start=277
  _CLEANREQUEST._serialized_end=308
  _CLEANREPLY._serialized_start=310
  _CLEANREPLY._serialized_end=339
  _SYSTEMCHECKREQUEST._serialized_start=341
  _SYSTEMCHECKREQUEST._serialized_end=378
  _SYSTEMCHECKREPLY._serialized_start=380
  _SYSTEMCHECKREPLY._serialized_end=415
  _BARBOT._serialized_start=418
  _BARBOT._serialized_end=572
# @@protoc_insertion_point(module_scope)
